export enum EnumTipoArticuloComida {
    HAMBURGUESAS = "HAMBURGUESAS",
    PANCHOS = "PANCHOS",
    EMPANADAS = "EMPANADAS",
    PIZZAS = "PIZZAS",
    LOMOS = "LOMOS",
    HELADO = "HELADO",
    PARRILLA = "PARRILLA",
    PASTAS = "PASTAS",
    SUSHI = "SUSHI",
    MILANESAS = "MILANESAS"
}
