export enum EnumMedida {
    KILOGRAMOS = "KILOGRAMOS",
    GRAMOS = "GRAMOS",
    LITROS = "LITROS",
    CENTIMETROS_CUBICOS = "CENTIMETROS_CUBICOS",
    PAQUETES = "PAQUETES",
    UNIDADES = "UNIDADES",
}
