export enum EnumEstadoPedido {
    ENTRANTES = 'ENTRANTES',
    ACEPTADOS = 'ACEPTADOS',
    COCINADOS = 'COCINADOS',
    ENTREGADOS = 'ENTREGADOS',
    RECHAZADOS = 'RECHAZADOS',
    EN_CAMINO = 'EN_CAMINO'
}
